[package]
name = "dasm"
version = "0.1.0"
edition = "2021"

[dependencies]
strum = { version = "0.27", features = ["derive"] }
rstest = "0.26.1"
instruction_proc_macro = { path = "../instruction_proc_macro" }
